#git alias
alias g="git"
alias gs="git status"
alias ga="git add"
alias gla="git pull --all"
alias gl="git pull --rebase origin"
alias gld="git pull --rebase origin develop"
alias glm="git pull --rebase origin master"
alias gc="git commit"
alias gcm="git commit -m"
alias gp="git push"
alias gm="git merge"
alias gmg="git merge guoxuan"
alias gb="git checkout"
alias gb="git checkout"
alias gbb="git checkout -b"
alias gbd="git checkout develop"
alias gbg="git checkout guoxuan"
alias gdt="git difftool -y"
alias gg="gbd;gl;gmg;gp;gbg;gld;"

#dir alias
alias c2="cd /d/code/AutoTestSystem"
alias c3="cd /d/code/ats_server"
alias cc="cd /d/work/code"
alias cdd="cd /d/"
alias cdl="cd /e/download"
alias ce="cd /e/"
alias cw="cd /d/work/"
alias c1="cd /d/work/code/zhdz"
alias l="ls -l"
alias ll="ls -l"

alias ali="ssh root@47.98.240.192"
alias rhl="ssh root@192.168.0.180"

